### ISSUE TITLE
Index error - string index out of range

### ISSUE THREAD

**Issue by ejk3052** [Simon-the-Shark/django-mapbox-location-field#12] opened 2020-06-09 14:52 UTC
Hello,

I get index error - string index out of range, when I save the form
<img width="1408" alt="Screenshot 2020-06-09 at 7 50 15 PM" src="https://user-images.githubusercontent.com/64918972/84163205-d68f1280-aa8e-11ea-976e-81162a9495ff.png">
<img width="1408" alt="Screenshot 2020-06-09 at 7 48 52 PM" src="https://user-images.githubusercontent.com/64918972/84163218-ddb62080-aa8e-11ea-93c2-c091de958994.png">

**Comment by Simon-the-Shark** [comment] 2020-06-20 11:32
Do you use the latest version of the package?

**Comment by Simon-the-Shark** [comment] 2020-06-23 08:12
Could you describe to me what have you exactly done in this example? I guess your field is not required. Did you post an empty form? Is your field read-only or did you typed something in the form field manually? More info could be useful in resolving this issue.

**Comment by Simon-the-Shark** [comment] 2020-07-08 11:03
Just share any information that you think may be useful in reproducing this bug and then resolving this issue.

**Comment by ejk3052** [comment] 2020-07-08 11:36
Dear  Szymon,

I went ahead without the location field for my initial work. I'm planning
to start rework on the same this week and hopefully will include location
field in the same. I will come back to you for any support.

Thanks for following.

Regards

Jay

**Comment by Simon-the-Shark** [comment] 2020-07-08 11:44
Okay. I'm closing this issue, but you can reopen it if you encounter the same bug or open a new one whenever my package causes any troubles. Good luck with your project!

**Comment by suyashgithub** [comment] 2020-07-15 09:14
> Hello,
> 
> I get index error - string index out of range, when I save the form
> <img alt="Screenshot 2020-06-09 at 7 50 15 PM" width="1408" src="https://user-images.githubusercontent.com/64918972/84163205-d68f1280-aa8e-11ea-976e-81162a9495ff.png">
> <img alt="Screenshot 2020-06-09 at 7 48 52 PM" width="1408" src="https://user-images.githubusercontent.com/64918972/84163218-ddb62080-aa8e-11ea-93c2-c091de958994.png">

i tried this code in model.py just put try block to handle type error and it fixed locally.
    def get_prep_value(self, value):
        if value is None:
            return value

        if isinstance(value, str):
            return self.save_string(value)
        try:
            return "{},{}".format(value[0], value[1])
        except TypeError:
            print('TypeError')

**Comment by Simon-the-Shark** [comment] 2020-07-16 13:39
@suyashgithub Of course, the try-except block eliminates error raising, but it probably doesn't eliminate the cause of this problem. It's a remedy only for symptoms of an issue. The get_prep_value() function is a crucial part of Django's field behavior (it converts the python value to the one that saved to the database) and the errors there shouldn't be ignored. 

I worked on a similar case in the #15 issue, but that was about the direct saving of strings to the database. According to your screenshot, your value is an empty string(''), so I guess it should satisfy the isinstance(value, str) if-check and then after self.save_string() affection saved to db without even entering the 45th line.

That's why I'm surprised that you still encounter this issue. I can take a closer look, but I need some details e.g. what's your configuration and what are you doing. I tried posting an empty form to a nullable field on my local machine and everything worked as expected.

**Comment by suyashgithub** [comment] 2020-07-16 14:48
I am using 
Python 3.6.2
Django==3.0.8
psql (11.3, server 10.8)

in my model i am using like this way

from mapbox_location_field.models import LocationField
class Customer(models.Model):
    location = LocationField(map_attrs={"track_location_button": True} )

**Comment by Simon-the-Shark** [comment] 2020-07-16 17:12
When exactly do you see this error? Are you doing something unexpected or just post a form? I'm asking because everything is wired. Your field is not nullable, but the value you have is an empty string? Apart from that, an empty string shouldn't cause an error like this in the latest version of my package.

I recommend you to try to run my [live demo](https://github.com/Simon-the-Shark/live_demo_django_mapbox_location_field) on your machine to see if this error still raise.

**Closed** 2020-07-31 07:48 UTC
Labels: more-information-needed
